// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	ID       string `json:"ID"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UpdateUserInput struct {
	ID       *string `json:"ID"`
	Name     *string `json:"name"`
	Password *string `json:"password"`
	IsActive *bool   `json:"isActive"`
}
